import { db } from '../src/lib/db';

async function main() {
  // Clear existing data
  await db.reviewerSession.deleteMany();
  await db.scholarship.deleteMany();

  const scholarships = [
    {
      name: "DOST-SEI Undergraduate Scholarship",
      provider: "Department of Science and Technology - Science Education Institute",
      description: "The DOST-SEI Undergraduate Scholarship Program aims to stimulate and nurture young Filipinos to pursue careers in science and technology. It provides financial assistance to deserving students who wish to pursue priority fields of study in science, mathematics, and engineering.",
      scholarshipType: "government",
      coverage: "full",
      coverageDetails: "Tuition and other school fees, monthly living allowance, book allowance, transportation allowance, summer allowance, group health and accident insurance",
      eligibleStrands: "STEM",
      minGPA: 83,
      maxAnnualIncome: 420000,
      requirements: "Filipino citizen, graduating SHS student, pursuing DOST priority courses, good moral character, good health, annual family income not exceeding PHP 420,000",
      deadline: "August to September annually",
      examType: "aptitude",
      examSubjects: "Science, Mathematics, English, Logical Reasoning",
      websiteUrl: "https://sei.dost.gov.ph/scholarship-program/undergraduate-scholarship-program",
      isActive: true,
    },
    {
      name: "CHED StuFAPs - Student Financial Assistance Programs",
      provider: "Commission on Higher Education",
      description: "CHED provides various Student Financial Assistance Programs (StuFAPs) to financially disadvantaged but deserving Filipino students who wish to pursue higher education. Programs include the State Scholarship Program (SSP) and Private Education Student Financial Assistance (PESFA).",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Tuition and other school fees, stipend, book allowance (amounts vary by program)",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 85,
      maxAnnualIncome: 300000,
      requirements: "Filipino citizen, financially disadvantaged, academically deserving, enrolled or planning to enroll in CHED-recognized programs, good moral character",
      deadline: "March to April annually",
      examType: "academic",
      examSubjects: "English, Mathematics, Science, Filipino, Abstract Reasoning",
      websiteUrl: "https://ched.gov.ph/stufaps/",
      isActive: true,
    },
    {
      name: "UP Oblation Scholarship",
      provider: "University of the Philippines",
      description: "The UP Oblation Scholarship is awarded to the top 50 UPCAT passers each year. It provides full financial support throughout the student's undergraduate studies at UP, recognizing exceptional academic excellence.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Full tuition, monthly living allowance, book allowance, transportation allowance, and dormitory accommodation",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 92,
      maxAnnualIncome: null,
      requirements: "Must be among the top 50 UPCAT passers, Filipino citizen, good moral character, must maintain a minimum GWA",
      deadline: "Synchronized with UPCAT application (typically September)",
      examType: "academic",
      examSubjects: "Mathematics, Science, Language Proficiency (English and Filipino), Reading Comprehension",
      websiteUrl: "https://up.edu.ph",
      isActive: true,
    },
    {
      name: "SM Foundation College Scholarship",
      provider: "SM Foundation Inc.",
      description: "The SM Foundation College Scholarship Program provides financial assistance to qualified and deserving students from low-income families. Scholars are given the opportunity to pursue college education in partner schools with full tuition coverage and other benefits.",
      scholarshipType: "private",
      coverage: "full",
      coverageDetails: "Full tuition, monthly allowance, part-time job opportunities during semestral and Christmas breaks at SM malls",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 88,
      maxAnnualIncome: 200000,
      requirements: "Filipino citizen, graduating SHS student with at least 88% general average, annual household income not exceeding PHP 200,000, good moral character, must pursue priority courses",
      deadline: "January to March annually",
      examType: "aptitude",
      examSubjects: "Mathematics, English, Logical Reasoning, General Knowledge",
      websiteUrl: "https://www.sm-foundation.org/education",
      isActive: true,
    },
    {
      name: "Ayala Foundation Scholarship",
      provider: "Ayala Foundation Inc.",
      description: "The Ayala Foundation provides scholarship opportunities to outstanding Filipino students who demonstrate academic excellence and a strong commitment to community service. The program aims to develop future leaders who will contribute to national development.",
      scholarshipType: "private",
      coverage: "full",
      coverageDetails: "Tuition and fees, monthly stipend, book allowance, leadership development training, mentorship",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 90,
      maxAnnualIncome: 500000,
      requirements: "Filipino citizen, academically excellent with at least 90% general average, active in community/extracurricular activities, good moral character, must maintain GWA",
      deadline: "February to April annually",
      examType: "aptitude",
      examSubjects: "English Proficiency, Critical Thinking, Numerical Reasoning, Current Events",
      websiteUrl: "https://www.ayalafoundation.org",
      isActive: true,
    },
    {
      name: "GSIS Educational Subsidy Program",
      provider: "Government Service Insurance System",
      description: "The GSIS Educational Subsidy Program provides financial assistance to children of active GSIS members who are low-income earners. The program covers tuition and other school fees for the duration of the scholar's college education.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Tuition and other school fees up to a maximum amount per semester",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 80,
      maxAnnualIncome: 300000,
      requirements: "Child of active GSIS member with salary not exceeding Step 6 or equivalent, Filipino citizen, enrolled in 4-5 year course, good moral character",
      deadline: "April to May annually",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.gsis.gov.ph",
      isActive: true,
    },
    {
      name: "Benilde Academic Scholarship",
      provider: "De La Salle-College of Saint Benilde",
      description: "The Benilde Academic Scholarship is awarded to students who have demonstrated exceptional academic performance. It covers full tuition and provides additional benefits to scholars throughout their stay in the college.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Full tuition waiver, book allowance, transportation allowance, priority enrollment",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 92,
      maxAnnualIncome: null,
      requirements: "Outstanding academic record with at least 92% general average, Filipino citizen, good moral character, must maintain required GWA each term",
      deadline: "January to March annually",
      examType: "academic",
      examSubjects: "English, Mathematics, Abstract Reasoning",
      websiteUrl: "https://www.benilde.edu.ph",
      isActive: true,
    },
    {
      name: "Megaworld Foundation Scholarship",
      provider: "Megaworld Foundation Inc.",
      description: "The Megaworld Foundation Scholarship Program supports financially disadvantaged but academically deserving students pursuing college degrees. Scholars are provided comprehensive financial support and are given opportunities for professional development.",
      scholarshipType: "private",
      coverage: "full",
      coverageDetails: "Full tuition and fees, monthly stipend, book allowance, leadership training, potential internship at Megaworld",
      eligibleStrands: "STEM, ABM",
      minGPA: 85,
      maxAnnualIncome: 250000,
      requirements: "Filipino citizen, graduating SHS with at least 85% general average, annual household income not exceeding PHP 250,000, good moral character, pursuing priority courses",
      deadline: "February to April annually",
      examType: "aptitude",
      examSubjects: "Mathematics, English, Logical Reasoning",
      websiteUrl: "https://www.megaworldfoundation.org",
      isActive: true,
    },
    {
      name: "PESFA - Private Education Student Financial Assistance",
      provider: "Commission on Higher Education",
      description: "The Private Education Student Financial Assistance (PESFA) program provides financial assistance to financially disadvantaged but deserving students who intend to enroll or are currently enrolled in private higher education institutions (HEIs).",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Tuition subsidy for private HEIs, book allowance, stipend",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 80,
      maxAnnualIncome: 300000,
      requirements: "Filipino citizen, financially disadvantaged, graduating SHS student or currently enrolled in private HEI, good moral character, must not be a recipient of any other government scholarship",
      deadline: "March to May annually",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://ched.gov.ph/stufaps/",
      isActive: true,
    },
    {
      name: "Mapua Financial Aid Program",
      provider: "Mapúa University",
      description: "Mapúa University offers various financial aid programs to academically excellent and financially disadvantaged students. These include academic scholarships, grants-in-aid, and student assistantships to ensure that no deserving student is deprived of quality education.",
      scholarshipType: "merit",
      coverage: "partial",
      coverageDetails: "Tuition discount ranging from 25% to 100% based on academic standing, plus possible stipend",
      eligibleStrands: "STEM",
      minGPA: 88,
      maxAnnualIncome: 400000,
      requirements: "Filipino citizen, high academic standing, good moral character, must maintain required GWA, may require annual income documentation",
      deadline: "March to May annually",
      examType: "academic",
      examSubjects: "Mathematics, Physics, English",
      websiteUrl: "https://www.mapua.edu.ph",
      isActive: true,
    },
    {
      name: "Tesda Scholarship Programs",
      provider: "Technical Education and Skills Development Authority",
      description: "TESDA offers various scholarship programs including the Training for Work Scholarship Program (TWSP) and the Private Education Student Financial Assistance (PESFA) to support students pursuing technical-vocational education and training.",
      scholarshipType: "government",
      coverage: "full",
      coverageDetails: "Full training cost, daily allowance, assessment fee, book allowance",
      eligibleStrands: "TVL",
      minGPA: 75,
      maxAnnualIncome: 250000,
      requirements: "Filipino citizen, at least 18 years old, must enroll in TESDA-registered programs, good moral character, financially disadvantaged",
      deadline: "Open enrollment (multiple intakes per year)",
      examType: "aptitude",
      examSubjects: "Trade-related knowledge, Basic Mathematics, English",
      websiteUrl: "https://www.tesda.gov.ph",
      isActive: true,
    },
    {
      name: "Ateneo College Scholarship Program",
      provider: "Ateneo de Manila University",
      description: "The Ateneo College Scholarship Program provides financial assistance to qualified students who demonstrate academic excellence and financial need. Scholarships range from partial to full coverage depending on the student's qualifications and financial circumstances.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Tuition and fees, book allowance, monthly living allowance, dormitory accommodation (for provincial scholars)",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 88,
      maxAnnualIncome: 500000,
      requirements: "Filipino citizen, strong academic record, demonstrated financial need, good moral character, must pass the Ateneo College Entrance Test (ACET)",
      deadline: "September to November annually",
      examType: "academic",
      examSubjects: "Mathematics, English, Science, Logical Reasoning, Abstract Reasoning",
      websiteUrl: "https://www.ateneo.edu",
      isActive: true,
    },
    {
      name: "DLSU Star Scholar Program",
      provider: "De La Salle University",
      description: "The DLSU Star Scholar Program is the university's most prestigious scholarship, awarded to top-performing students. It provides comprehensive financial support and academic enrichment opportunities to develop outstanding scholars and future leaders.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Full tuition and fees, monthly stipend, book allowance, accommodation allowance, enrichment activities, international exchange opportunities",
      eligibleStrands: "STEM, ABM",
      minGPA: 90,
      maxAnnualIncome: null,
      requirements: "Top performing SHS graduate, must pass DLSU College Admission Test with high scores, Filipino citizen, good moral character",
      deadline: "October to December annually",
      examType: "academic",
      examSubjects: "Mathematics, Science, English, Filipino, Abstract Reasoning",
      websiteUrl: "https://www.dlsu.edu.ph",
      isActive: true,
    },
    {
      name: "PCSO Medical Scholarship Program",
      provider: "Philippine Charity Sweepstakes Office",
      description: "The PCSO Medical Scholarship Program provides financial assistance to deserving students who wish to pursue medical and health-related courses. The program aims to increase the number of healthcare professionals serving the Filipino people.",
      scholarshipType: "government",
      coverage: "full",
      coverageDetails: "Full tuition and fees, monthly living allowance, book allowance, uniform allowance",
      eligibleStrands: "STEM",
      minGPA: 85,
      maxAnnualIncome: 300000,
      requirements: "Filipino citizen, must be pursuing medical/health-related courses, good moral character, financially disadvantaged, must serve in a government hospital after graduation",
      deadline: "March to May annually",
      examType: "academic",
      examSubjects: "Biology, Chemistry, Physics, Mathematics",
      websiteUrl: "https://www.pcso.gov.ph",
      isActive: true,
    },
    {
      name: "Robinsons Scholarship Program",
      provider: "Robinsons Land Corporation",
      description: "The Robinsons Scholarship Program supports academically excellent but financially disadvantaged Filipino students pursuing college degrees. The program provides financial assistance and opportunities for professional growth.",
      scholarshipType: "private",
      coverage: "partial",
      coverageDetails: "Tuition assistance, monthly allowance, potential internship opportunities",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 85,
      maxAnnualIncome: 250000,
      requirements: "Filipino citizen, graduating SHS with at least 85% general average, annual household income not exceeding PHP 250,000, good moral character",
      deadline: "February to April annually",
      examType: "aptitude",
      examSubjects: "English, Mathematics, Logical Reasoning",
      websiteUrl: "https://www.robinsonsland.com",
      isActive: true,
    },
    {
      name: "UST Academic Scholarship",
      provider: "University of Santo Tomas",
      description: "UST offers academic scholarships to students who have shown exceptional academic performance. The university provides various levels of financial assistance based on academic merit, supporting the holistic development of Thomasian scholars.",
      scholarshipType: "merit",
      coverage: "partial",
      coverageDetails: "Tuition discount ranging from 50% to 100% depending on academic standing, book allowance for top scholars",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 90,
      maxAnnualIncome: null,
      requirements: "Exceptional academic performance, must pass UST Entrance Test (USTET), Filipino citizen, good moral character, must maintain required GWA",
      deadline: "September to November annually",
      examType: "academic",
      examSubjects: "Mathematics, Science, English, Filipino, Abstract Reasoning",
      websiteUrl: "https://www.ust.edu.ph",
      isActive: true,
    },
  ];

  for (const scholarship of scholarships) {
    await db.scholarship.create({ data: scholarship });
  }

  console.log(`Seeded ${scholarships.length} scholarships`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
