import { db } from '../src/lib/db';

async function main() {
  // Clear existing data
  await db.reviewerSession.deleteMany();
  await db.scholarship.deleteMany();

  const scholarships = [
    // ═══════════════════════════════════════════════════════════════
    // PUP-FUNDED PROGRAMS
    // ═══════════════════════════════════════════════════════════════
    {
      name: "PUP Entrance Scholarship Program",
      provider: "Polytechnic University of the Philippines",
      description: "The Entrance Scholarship is awarded to incoming first-year students who passed the PUP College Entrance Test (PUPCET). It covers full tuition and other school fees. Scholars receive a Certification as 'Entrance Scholar of PUP' and their talents are nurtured through various trainings. Categories include: (1) Top 10 of graduating class from public HS with 500+ graduates, (2) Cultural Artist, (3) Student Athlete, (4) Creative Media Artist, (5) Campus Journalist, (6) Differently-abled learners, (7) ALS Graduate, (8) Indigenous People, (9) Solo Parent, (10) SK Official, (11) First Generation College Applicant from Indigent Family.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Full tuition and other school fees, Certification as 'Entrance Scholar of PUP', talent development through various trainings",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 85,
      maxAnnualIncome: null,
      priorityCourses: "All PUP undergraduate degree programs",
      requirements: "Certification from School Principal (with dry seal), PUPCET passer, specific documents per category (PWD ID, ALS Certificate, IP Certificate, Barangay Certification, etc.)",
      deadline: "During enrollment period (apply during schedule of enrollment and submit documentary requirements)",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.pup.edu.ph/students/scholarships",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "PUP Resident Scholarship (President's Lister)",
      provider: "Polytechnic University of the Philippines",
      description: "The President's Lister / University Scholarship is awarded to currently enrolled PUP undergraduate students with exemplary academic performance. Students with a General Weighted Average (GWA) of 1.50 or better, with no grade lower than 2.5 in any subject, qualify for this scholarship.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Full tuition fee discount, certificate of recognition, financial grant",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 95,
      maxAnnualIncome: null,
      priorityCourses: "All PUP undergraduate degree programs",
      requirements: "Currently enrolled PUP student, Regular status, GWA of at least 1.50, no grade below 2.5, application submitted by section through class president/representative",
      deadline: "One week after the Adjustment Period of each semester",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.pup.edu.ph/studentservices/osfa/services",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "PUP Resident Scholarship (Dean's Lister)",
      provider: "Polytechnic University of the Philippines",
      description: "The Dean's Lister / College Scholarship is awarded to currently enrolled PUP undergraduate students with strong academic performance. Students with a General Weighted Average (GWA) of 1.75 or better, with no grade lower than 2.5 in any subject, qualify for this scholarship.",
      scholarshipType: "merit",
      coverage: "partial",
      coverageDetails: "Partial tuition fee discount, certificate of recognition",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 92,
      maxAnnualIncome: null,
      priorityCourses: "All PUP undergraduate degree programs",
      requirements: "Currently enrolled PUP student, Regular status, GWA of at least 1.75, no grade below 2.5, application submitted by section",
      deadline: "One week after the Adjustment Period of each semester",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.pup.edu.ph/studentservices/osfa/services",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "PUP Student Assistantship Program",
      provider: "Polytechnic University of the Philippines",
      description: "The Student Assistantship Program is a term of employment applicable to any PUP student of regular academic status. Student assistants work not more than 24 hours a week or 100 hours a month at a compensation rate of PHP 25/hour. The term of employment is subject to renewal every semester.",
      scholarshipType: "financial-need",
      coverage: "partial",
      coverageDetails: "PHP 25/hour compensation, up to 100 hours/month (approximately PHP 2,500/month)",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 80,
      maxAnnualIncome: null,
      priorityCourses: "All PUP undergraduate degree programs",
      requirements: "Currently enrolled PUP student, at least 2nd Year College, Regular status, passed all enrolled subjects during last semester, endorsed by head of the Office to be served",
      deadline: "One week after the Adjustment Period of each semester",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.pup.edu.ph/students/scholarships",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "PUP Cash Award for Board Exam Topnotchers",
      provider: "Polytechnic University of the Philippines",
      description: "PUP provides cash awards to graduates who top their respective board/licensure examinations. This program recognizes and rewards academic excellence and professional achievement among PUP alumni.",
      scholarshipType: "merit",
      coverage: "partial",
      coverageDetails: "Cash award - amount varies by ranking in board exam",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 75,
      maxAnnualIncome: null,
      priorityCourses: "All PUP degree programs with board/licensure exams",
      requirements: "PUP graduate, board exam topnotcher, must have taken the board exam within the qualifying period",
      deadline: "N/A (automatic upon board exam results)",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.pup.edu.ph/studentservices/osfa/",
      isActive: true,
      isAcceptingApplications: false,
    },

    // ═══════════════════════════════════════════════════════════════
    // GOVERNMENT-FUNDED PROGRAMS (available to PUP students)
    // ═══════════════════════════════════════════════════════════════
    {
      name: "Tertiary Education Subsidy (TES) - RA 10931",
      provider: "UniFAST / Commission on Higher Education",
      description: "The Tertiary Education Subsidy (TES) is a program under RA 10931 (Universal Access to Quality Tertiary Education Act). It provides financial assistance to students in SUCs, LUCs, and private HEIs. PUP, as an SUC, is a beneficiary institution. Priority is given to students in Listahanan 2.0 and 4Ps households.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "₱20,000/AY for SUC/LUC students; additional ₱10,000 for PWD, ₱8,000 one-time for board exam takers",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 75,
      maxAnnualIncome: 400000,
      priorityCourses: "All CHED-recognized degree programs",
      requirements: "Filipino citizen, enrolled in SUC/LUC/private HEI, demonstrates financial need, meets admission/retention requirements, no previous undergraduate degree, not overstaying, not expelled from any HEI. Apply via UniFAST Portal.",
      deadline: "Applications via UniFAST Portal (opens per AY; shortlisted applicants confirmed by UniFAST)",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://unifast.gov.ph/tes.html",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "Tulong Dunong Program (TDP)",
      provider: "UniFAST / Commission on Higher Education",
      description: "The Tulong Dunong Program (TDP) is a subsidy under the TES Program that supports at least the partial cost of tertiary education, inclusive of education-related expenses. It is for students whose household income does not exceed PHP 400,000 and who are not beneficiaries of TES or other CHED scholarship programs.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "₱7,500 per regular semester, subject to prioritization and fund availability",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 75,
      maxAnnualIncome: 400000,
      priorityCourses: "All CHED-recognized degree programs",
      requirements: "Filipino citizen, combined household gross income not exceeding ₱400,000, enrolled in first undergraduate degree in SUC/LUC/private HEI, NOT a beneficiary of TES, CHED Scholarship Programs, or other national government-funded StuFAPs",
      deadline: "Per AY, as announced by CHED/UniFAST",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://unifast.gov.ph/tes.html",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "CHED Scholarship Program (CSP)",
      provider: "Commission on Higher Education",
      description: "The CHED Scholarship Program (CSP), also known as the CHED Merit Scholarship Program (CMSP), provides financial assistance to incoming freshman and college-level Filipino students who are academically deserving and financially disadvantaged. Also known as the CHED Merit Scholarship Program (CMSP), it covers tuition and other school fees, book and connectivity allowance, and a stipend for living expenses. PUP is a CHED-recognized institution.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Tuition and other school fees, stipend, book allowance - amounts vary",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 90,
      maxAnnualIncome: 500000,
      priorityCourses: "BS Engineering, BS Computer Science, BS Information Technology, BS Accountancy, BS Education, BS Nursing, BS Agriculture, BS Social Work, BS Psychology, BS Biology, BS Chemistry, BS Mathematics, BS Statistics",
      requirements: "Filipino citizen, incoming freshman or college-level, academically deserving (90% GWA for freshmen), financially disadvantaged, good moral character, must not be recipient of other government-funded scholarship",
      deadline: "Per AY as announced by CHED Regional Offices (typically May-June)",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://unifast.gov.ph/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "ACEF-GIAHEP (Agricultural Competitiveness Enhancement Fund - Grants-in-Aid for Higher Education Program)",
      provider: "Commission on Higher Education",
      description: "ACEF-GIAHEP provides scholarship grants to students pursuing agriculture, forestry, fisheries, and veterinary medicine education. This CHED-administered program aims to develop human resources in agriculture and related fields.",
      scholarshipType: "government",
      coverage: "full",
      coverageDetails: "Tuition and other school fees, stipend, book allowance",
      eligibleStrands: "STEM, TVL",
      minGPA: 85,
      maxAnnualIncome: 300000,
      priorityCourses: "BS Agriculture, BS Agricultural Engineering, BS Agricultural Economics, BS Forestry, BS Fisheries, BS Veterinary Medicine, BS Agricultural Technology, BS Animal Science, BS Crop Science, BS Food Technology, BS Biology, BS Chemistry, BS Environmental Science",
      requirements: "Filipino citizen, graduating SHS student or currently enrolled in college, pursuing agriculture/fisheries/forestry-related courses, good moral character, financially disadvantaged",
      deadline: "Per AY as announced by CHED Regional Offices",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://caraga.ched.gov.ph/acef-giahep",
      isActive: true,
      isAcceptingApplications: false,
    },

    // ═══════════════════════════════════════════════════════════════
    // PRIVATELY-FUNDED PROGRAMS (available to PUP students)
    // ═══════════════════════════════════════════════════════════════
    {
      name: "SM Foundation College Scholarship",
      provider: "SM Foundation Inc.",
      description: "The SM Foundation College Scholarship Program provides full financial support to qualified and deserving students from low-income families. PUP is a partner school (Sta. Mesa, San Juan, Quezon City, Taguig campuses). Scholars receive full tuition coverage and part-time job opportunities at SM malls.",
      scholarshipType: "private",
      coverage: "full",
      coverageDetails: "Full tuition, monthly allowance, part-time job opportunities during semestral and Christmas breaks at SM malls",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 88,
      maxAnnualIncome: 200000,
      priorityCourses: "BS Accountancy, BS Civil Engineering, BS Electrical Engineering, BS Mechanical Engineering, BS Computer Engineering, BS Electronics Engineering, BS Computer Science, BS Information Technology, BS Education, BS Nursing, BS Food Technology, BS Agriculture, BS Architecture, BS Business Administration, BS Hospitality Management",
      requirements: "Filipino citizen, graduating SHS with at least 88% general average, annual household income not exceeding PHP 200,000, good moral character, must pursue priority courses",
      deadline: "Typically Feb 1 - Mar 31 annually",
      examType: "aptitude",
      examSubjects: "Mathematics, English, Logical Reasoning",
      websiteUrl: "https://www.sm-foundation.org/what_we_do/college-scholarship-program",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "Tzu Chi Foundation Educational Assistance Program",
      provider: "Buddhist Compassion Relief Tzu Chi Foundation Philippines, Inc.",
      description: "The Tzu Chi Foundation Philippines provides educational assistance to financially challenged but academically deserving students. PUP is a partner institution. The program supports students who are regular students with at least 82% GWA and belong to an indigent or economically challenged family. Applicants must be residents of Metro Manila or areas in Rizal near NCR.",
      scholarshipType: "private",
      coverage: "partial",
      coverageDetails: "Educational assistance for tuition and school-related expenses",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 82,
      maxAnnualIncome: 250000,
      priorityCourses: "BS Accountancy, BS Engineering, BS Computer Science, BS Information Technology, BS Nursing, BS Education, BS Psychology, BS Business Administration, BS Social Work, BS Biology, BS Chemistry, BS Mathematics, BS Industrial Technology",
      requirements: "Filipino citizen, 1st-year college student (incoming 2nd year at time of application), GWA of at least 2.25 (82%), regular student, financially challenged, resident of Metro Manila or Rizal near NCR, must pass interview and agree to home visitation. Required documents: Latest Report Card, Registration Form, 1x1 ID Picture, Autobiography, Recent Family Picture, House Photos, Utility Bills, Sketch Map, ITR/Pay Slip, Barangay Certificate of Indigency.",
      deadline: "April 30, 2026 (application now open)",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://tzuchi.org.ph/apply",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "Megaworld Foundation Scholarship",
      provider: "Megaworld Foundation Inc.",
      description: "Megaworld Foundation is a PUP OSFA benefactor that provides scholarship support to financially disadvantaged but academically deserving PUP students pursuing college degrees.",
      scholarshipType: "private",
      coverage: "full",
      coverageDetails: "Full tuition and fees, monthly stipend, book allowance, leadership training, potential internship at Megaworld",
      eligibleStrands: "STEM, ABM",
      minGPA: 85,
      maxAnnualIncome: 250000,
      priorityCourses: "BS Accountancy, BS Civil Engineering, BS Electrical Engineering, BS Mechanical Engineering, BS Computer Engineering, BS Electronics Engineering, BS Computer Science, BS Information Technology, BS Architecture, BS Business Administration, BS Real Estate Management, BS Interior Design, BS Marketing Management",
      requirements: "Filipino citizen, PUP student with at least 85% general average, annual household income not exceeding PHP 250,000, good moral character, pursuing priority courses",
      deadline: "Subject to deadline set by the benefactor (posted in OSFA Bulletin Board and FB Page: PUP Scholarship)",
      examType: "aptitude",
      examSubjects: "Mathematics, English, Logical Reasoning",
      websiteUrl: "https://www.megaworldfoundation.com/scholarship/apply/form",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "Security Bank Foundation Scholarship",
      provider: "Security Bank Foundation, Inc.",
      description: "Security Bank Foundation is a PUP OSFA benefactor that provides scholarship grants to academically deserving and financially challenged PUP students.",
      scholarshipType: "private",
      coverage: "partial",
      coverageDetails: "Tuition assistance and educational support as stipulated in MOA",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 85,
      maxAnnualIncome: 300000,
      priorityCourses: "BS Accountancy, BS Business Administration, BS Computer Science, BS Information Technology, BS Engineering, BS Economics, BS Banking and Finance",
      requirements: "Filipino citizen, PUP student, good academic standing, financially challenged, subject to evaluation by OSFA and Security Bank Foundation criteria per MOA provisions",
      deadline: "Subject to deadline set by the benefactor (posted in OSFA Bulletin Board and FB Page: PUP Scholarship)",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.securitybank.com/foundation/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "Aboitiz Foundation Scholarship",
      provider: "Aboitiz Foundation, Inc. and AP Renewables, Inc.",
      description: "Aboitiz Foundation is a PUP OSFA benefactor providing scholarship support to PUP students, particularly those in engineering and technology-related programs.",
      scholarshipType: "private",
      coverage: "partial",
      coverageDetails: "Educational financial assistance per MOA",
      eligibleStrands: "STEM",
      minGPA: 85,
      maxAnnualIncome: 300000,
      priorityCourses: "BS Electrical Engineering, BS Mechanical Engineering, BS Civil Engineering, BS Computer Engineering, BS Electronics Engineering, BS Computer Science, BS Information Technology, BS Environmental Science, BS Geology",
      requirements: "Filipino citizen, PUP student, good academic standing, pursuing priority courses, financially challenged, subject to MOA provisions",
      deadline: "Subject to deadline set by the benefactor (posted in OSFA Bulletin Board and FB Page: PUP Scholarship)",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.aboitizfoundation.org/",
      isActive: true,
      isAcceptingApplications: false,
    },

    // ═══════════════════════════════════════════════════════════════
    // EXISTING SCHOLARSHIPS KEPT (also available to PUP students)
    // ═══════════════════════════════════════════════════════════════
    {
      name: "DOST-SEI Undergraduate Scholarship",
      provider: "Department of Science and Technology - Science Education Institute",
      description: "The DOST-SEI Undergraduate Scholarship Program aims to stimulate and nurture young Filipinos to pursue careers in science and technology. It provides financial assistance to deserving students who wish to pursue priority fields of study in science, mathematics, and engineering. Available to PUP STEM students.",
      scholarshipType: "government",
      coverage: "full",
      coverageDetails: "Tuition and other school fees, monthly living allowance, book allowance, transportation allowance, summer allowance, group health and accident insurance",
      eligibleStrands: "STEM",
      minGPA: 83,
      maxAnnualIncome: 420000,
      priorityCourses: "BS Physics, BS Chemistry, BS Mathematics, BS Biology, BS Computer Science, BS Civil Engineering, BS Electrical Engineering, BS Mechanical Engineering, BS Chemical Engineering, BS Electronics Engineering, BS Industrial Engineering, BS Marine Science, BS Statistics, BS Geology, BS Environmental Science, BS Material Science, BS Agriculture, BS Food Technology, BS Medical Technology, BS Nursing, BS Pharmacy, BS Dental Medicine, BS Physical Therapy, BS Radiologic Technology",
      requirements: "Filipino citizen, graduating SHS student, pursuing DOST priority courses, good moral character, good health, annual family income not exceeding PHP 420,000",
      deadline: "AY 2026-2027 applications are now CLOSED (deadline was Nov 21, 2025; exam held Feb 21-22, 2026). Next cycle typically opens August-November annually.",
      examType: "aptitude",
      examSubjects: "Science, Mathematics, English, Logical Reasoning",
      websiteUrl: "https://ugrad.science-scholarships.ph/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "GBF STEM College Scholarship",
      provider: "Gokongwei Brothers Foundation",
      description: "The GBF STEM College Scholarship (formerly the Gokongwei Group STEM Scholarship for Excellence) supports outstanding college students pursuing GBF priority STEM courses. Available to PUP students. The program is funded by the Gokongwei Brothers Foundation, the corporate social responsibility arm of the Gokongwei Group which includes JG Summit, Robinsons Land, and Cebu Pacific.",
      scholarshipType: "private",
      coverage: "partial",
      coverageDetails: "PHP 80,000 to PHP 120,000 annual financial assistance, access to scholar development programs, on-the-job training opportunities at Gokongwei Group companies",
      eligibleStrands: "STEM",
      minGPA: 85,
      maxAnnualIncome: 500000,
      priorityCourses: "BS Computer Science, BS Data Science, BS Chemical Engineering, BS Civil Engineering, BS Electrical Engineering, BS Electronics Engineering, BS Industrial Engineering, BS Mechanical Engineering, BS Computer Engineering, BS Information Technology, BS Mathematics, BS Physics, BS Chemistry, BS Biology, BS Statistics, BS Environmental Science, BS Food Technology, BS Material Science Engineering, BS Manufacturing Engineering",
      requirements: "Filipino citizen, graduating SHS with at least 85% general average, pursuing GBF priority STEM courses, good moral character, active in extracurricular activities",
      deadline: "NOW OPEN: AY 2026-2027 deadline is May 30, 2026. Apply at bit.ly/GBFSTEMCollege-OL2026. Typically opens January-May annually.",
      examType: "aptitude",
      examSubjects: "Mathematics, English, Logical Reasoning, Science",
      websiteUrl: "https://www.gokongweibrothersfoundation.org/programs/gbf-stem-scholarship-for-excellence",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "PCSO Educational Assistance Program",
      provider: "Philippine Charity Sweepstakes Office",
      description: "The PCSO Educational Assistance Program provides financial assistance to qualified Filipino college students to help cover tuition and other school expenses. The program is open to all currently enrolled college students in any school, college, or university in the Philippines, including PUP. Applications are accepted through the eGovPH Super App or via email submission for applicants outside Metro Manila.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Financial assistance for tuition and other school fees (₱2,000 to ₱10,000 per qualified student; actual amount varies based on student's outstanding balance, branch, and availability of PCSO funds)",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 75,
      maxAnnualIncome: null,
      priorityCourses: "Open to all college programs",
      requirements: "Filipino citizen, currently enrolled college student in any public or private school/college/university in the Philippines, must submit complete documentary requirements (Certificate of Enrollment, valid government-issued IDs of student and parent/guardian, photocopy of Student ID, certified true copy of billing statement, academic transcript or latest report card, duly accomplished PCSO Educational Assistance Form with 2x2 photo)",
      deadline: "No fixed deadline (applications are currently ongoing; apply as soon as requirements are complete; schedules may differ per branch while funds are available)",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://governmentph.com/pcso-educational-assistance",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "TESDA Scholarship Programs",
      provider: "Technical Education and Skills Development Authority",
      description: "TESDA offers multiple scholarship programs to support Filipinos pursuing technical-vocational education and training (TVET). Available to TVL students entering PUP Institute of Technology. Programs include the Training for Work Scholarship Program (TWSP), Special Training for Employment Program (STEP), Tulong Trabaho Scholarship Program (TTSP), and Universal Access to Quality Tertiary Education Act (UAQTEA) programs. Applications are submitted online through the TESDA Biometric-Enabled Scholarship Registration System (BSRS).",
      scholarshipType: "government",
      coverage: "full",
      coverageDetails: "Free training cost, free competency assessment fee, Training Support Fund of ₱160/day, starter toolkits (for STEP scholars), ₱500 PPE allowance, ₱500 internet/data allowance, 1-year GSIS accident insurance coverage",
      eligibleStrands: "TVL",
      minGPA: 75,
      maxAnnualIncome: 250000,
      priorityCourses: "Automotive Servicing NC II, Electrical Installation and Maintenance NC II, Welding (SMAW/GTAW) NC II, Computer Systems Servicing NC II, Caregiving NC II, Culinary Arts NC II, Food and Beverage Services NC II, Housekeeping NC II, Bartending NC II, Bookkeeping NC III, Shielded Metal Arc Welding NC II, Plumbing NC II, Masonry NC II, Carpentry NC II, Refrigeration and Air-Conditioning NC II, Electronic Products Assembly and Servicing NC II",
      requirements: "Filipino citizen, at least 18 years old (15 years old for select programs), must enroll in TESDA-registered programs, good moral character, financially disadvantaged, able to attend training sessions, must register and apply via BSRS (bsrs.tesda.gov.ph)",
      deadline: "Open enrollment year-round (multiple intakes; apply anytime online via the TESDA BSRS portal at bsrs.tesda.gov.ph or visit any TESDA Regional/Provincial Office)",
      examType: "aptitude",
      examSubjects: "Trade-related knowledge, Basic Mathematics, English",
      websiteUrl: "https://bsrs.tesda.gov.ph/",
      isActive: true,
      isAcceptingApplications: true,
    },

    // ═══════════════════════════════════════════════════════════════
    // GENERAL PUBLIC SCHOLARSHIPS (re-added to serve all Filipino students)
    // ═══════════════════════════════════════════════════════════════
    {
      name: "UP Oblation Scholarship",
      provider: "University of the Philippines",
      description: "The UP Oblation Scholarship is the most prestigious scholarship awarded by the University of the Philippines to the top 50 qualifiers of the UPCAT. It provides full tuition coverage and a monthly allowance. Automatic award for top UPCAT performers — no separate application required.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Full tuition waiver, book allowance, transportation allowance, priority enrollment",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 92,
      maxAnnualIncome: null,
      priorityCourses: "All UP undergraduate degree programs (BS Physics, BS Chemistry, BS Mathematics, BS Biology, BS Computer Science, BS Engineering, BS Economics, BA Political Science, BA Psychology, BA Communication, BS Public Health, BS Architecture, BS Fine Arts, and more)",
      requirements: "Must be among the top 50 UPCAT passers, Filipino citizen, good moral character, must maintain a minimum GWA",
      deadline: "UPCAT 2027 applications are now CLOSED (extended deadline was April 13, 2026; exam Aug 1-2, 2026). Scholarship is automatic for top 50 qualifiers. Next UPCAT typically opens March annually.",
      examType: "academic",
      examSubjects: "Mathematics, Science, Language Proficiency (English and Filipino), Reading Comprehension",
      websiteUrl: "https://upcat.up.edu.ph/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "Benilde Academic Scholarship",
      provider: "De La Salle-College of Saint Benilde",
      description: "The Benilde Academic Scholarship is awarded to outstanding students who demonstrate exceptional academic performance. It covers full tuition and provides additional benefits including book and transportation allowances. Open to top-performing SHS graduates aiming to enroll at Benilde.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Full tuition waiver, book allowance, transportation allowance, priority enrollment",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 92,
      maxAnnualIncome: null,
      priorityCourses: "BS Business Administration, BS Accountancy, BS Computer Science, BS Information Systems, BS Interior Design, BS Architecture, AB Multimedia Arts, AB Film, AB Music Production, AB Photography, AB Fashion Design and Merchandising, BS Hospitality Management, BS Tourism Management, BS Human Resource Management, AB Animation, AB Industrial Design",
      requirements: "Outstanding academic record with at least 92% general average, Filipino citizen, good moral character, must maintain required GWA each term",
      deadline: "AY 2026-2027 scholarship applications are now CLOSED (deadline was Jan 15, 2026). Admissions deadline was May 12, 2026. Next scholarship cycle typically opens September-January annually.",
      examType: "academic",
      examSubjects: "English, Mathematics, Abstract Reasoning",
      websiteUrl: "https://apply.benilde.edu.ph/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "Mapua Financial Aid Program",
      provider: "Mapua University",
      description: "The Mapua Financial Aid Program provides tuition discounts ranging from 25% to 100% based on academic standing to deserving students. It also includes a possible stipend for top qualifiers. Aimed at supporting students in engineering, technology, and science programs at Mapua University.",
      scholarshipType: "merit",
      coverage: "partial",
      coverageDetails: "Tuition discount ranging from 25% to 100% based on academic standing, plus possible stipend",
      eligibleStrands: "STEM",
      minGPA: 88,
      maxAnnualIncome: 400000,
      priorityCourses: "BS Civil Engineering, BS Electrical Engineering, BS Mechanical Engineering, BS Chemical Engineering, BS Electronics Engineering, BS Computer Engineering, BS Industrial Engineering, BS Computer Science, BS Information Technology, BS Architecture, BS Biology, BS Chemistry, BS Physics, BS Mathematics, BS Environmental Engineering, BS Geology, BS Biomedical Engineering",
      requirements: "Filipino citizen, high academic standing, good moral character, must maintain required GWA, may require annual income documentation",
      deadline: "AY 2026-2027 ETY Scholarship applications are now CLOSED (cutoff was Feb 6, 2026). IBFAP application period: Mar 2 - May 15, 2026. Next ETY cycle typically October-February annually.",
      examType: "academic",
      examSubjects: "Mathematics, Physics, English",
      websiteUrl: "https://www.mapua.edu.ph/pages/admissions/mapua-scholarships/financial-assistance",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "Ateneo College Scholarship Program",
      provider: "Ateneo de Manila University",
      description: "The Ateneo College Scholarship Program provides full financial support to academically excellent and financially disadvantaged students. Coverage includes tuition, fees, living allowance, and dormitory accommodation for provincial scholars. One of the most comprehensive scholarship packages in the country.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Tuition and fees, book allowance, monthly living allowance, dormitory accommodation (for provincial scholars)",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 88,
      maxAnnualIncome: 500000,
      priorityCourses: "BS Management, BS Management Engineering, BS Legal Management, BS Accountancy, BS Computer Science, BS Information Systems, BS Electronics Engineering, BS Physics, BS Chemistry, BS Biology, BS Mathematics, AB Economics, AB Psychology, AB Political Science, AB Communication, AB Philosophy, BS Public Health, BS Education",
      requirements: "Filipino citizen, strong academic record, demonstrated financial need, good moral character, must pass the Ateneo College Entrance Test (ACET)",
      deadline: "AY 2026-2027 scholarship applications are now CLOSED (deadline was Dec 19, 2025; ACET held Jan 17, 2026). Next cycle typically opens September-December annually.",
      examType: "academic",
      examSubjects: "Mathematics, English, Science, Logical Reasoning, Abstract Reasoning",
      websiteUrl: "https://www.ateneo.edu/college/scholarships/apply",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "DLSU Star Scholar Program",
      provider: "De La Salle University",
      description: "The DLSU Star Scholar Program is the most prestigious scholarship at De La Salle University, awarded to top-performing SHS graduates who excel in the DLSU College Admission Test (DCAT). It provides full tuition, monthly stipend, book allowance, accommodation allowance, and enrichment activities including international exchange opportunities.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Full tuition and fees, monthly stipend, book allowance, accommodation allowance, enrichment activities, international exchange opportunities",
      eligibleStrands: "STEM, ABM",
      minGPA: 90,
      maxAnnualIncome: null,
      priorityCourses: "BS Computer Science, BS Computer Engineering, BS Electronics Engineering, BS Chemical Engineering, BS Civil Engineering, BS Industrial Engineering, BS Manufacturing Engineering, BS Mechanical Engineering, BS Mathematics, BS Physics, BS Chemistry, BS Biology, BS Accountancy, BS Business Administration, BS Economics, BS Statistics, BS Human Biology",
      requirements: "Top performing SHS graduate, must pass DLSU College Admission Test (DCAT) with high scores, Filipino citizen, good moral character",
      deadline: "AY 2026-2027 DCAT regular applications are now CLOSED (period was Sep 1, 2025 - Jan 10, 2026). Special DCAT period was Feb 2 - Apr 4, 2026. St. La Salle Financial Aid: Apr 17 - May 17, 2026. Next cycle typically opens September annually.",
      examType: "academic",
      examSubjects: "Mathematics, Science, English, Filipino, Abstract Reasoning",
      websiteUrl: "https://www.dlsu.edu.ph/admission/scholarship",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "UST Academic Scholarship",
      provider: "University of Santo Tomas",
      description: "The UST Academic Scholarship provides tuition discounts ranging from 50% to 100% to students with exceptional academic performance. It also includes a book allowance for top scholars. Available to qualified students who pass the UST Entrance Test (USTET) and maintain the required general weighted average.",
      scholarshipType: "merit",
      coverage: "partial",
      coverageDetails: "Tuition discount ranging from 50% to 100% depending on academic standing, book allowance for top scholars",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 90,
      maxAnnualIncome: null,
      priorityCourses: "BS Architecture, BS Interior Design, BS Chemical Engineering, BS Civil Engineering, BS Electrical Engineering, BS Electronics Engineering, BS Industrial Engineering, BS Mechanical Engineering, BS Computer Science, BS Information Technology, BS Accountancy, BS Business Administration, BS Nursing, BS Medical Technology, BS Pharmacy, BS Biology, BS Chemistry, BS Physics, BS Mathematics, BS Psychology, BS Education, AB Communication, AB Economics, AB Literature, AB Philosophy, BS Physical Therapy, BS Nutrition and Dietetics, BS Medical Laboratory Science",
      requirements: "Exceptional academic performance, must pass UST Entrance Test (USTET), Filipino citizen, good moral character, must maintain required GWA",
      deadline: "AY 2026-2027 scholarship applications are now CLOSED (period was Aug 8, 2025 - Jan 19, 2026; USTET deadline Jan 23, 2026). Next cycle typically opens August-January annually.",
      examType: "academic",
      examSubjects: "Mathematics, Science, English, Filipino, Abstract Reasoning",
      websiteUrl: "https://ustet.ust.edu.ph/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "CHED StuFAPs - Student Financial Assistance Programs",
      provider: "Commission on Higher Education",
      description: "The CHED Student Financial Assistance Programs (StuFAPs) provide financial assistance to qualified and deserving Filipino students enrolled in CHED-recognized programs. Coverage includes tuition, other school fees, stipend, and book allowance. Intended for financially disadvantaged but academically deserving students.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Tuition and other school fees up to PHP 120,000, stipend, book allowance (amounts vary by program)",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 85,
      maxAnnualIncome: 300000,
      priorityCourses: "BS Accountancy, BS Engineering, BS Computer Science, BS Information Technology, BS Nursing, BS Medical Technology, BS Pharmacy, BS Agriculture, BS Education, BS Social Work, BS Psychology, BS Biology, BS Chemistry, BS Mathematics, BS Statistics, BS Physical Therapy, BS Dentistry, BS Nutrition and Dietetics",
      requirements: "Filipino citizen, financially disadvantaged, academically deserving, enrolled or planning to enroll in CHED-recognized programs, good moral character",
      deadline: "AY 2025-2026 applications are now CLOSED (deadline was June 20, 2025). Next cycle typically opens May-June annually via CHED Regional Offices.",
      examType: "academic",
      examSubjects: "English, Mathematics, Science, Filipino, Abstract Reasoning",
      websiteUrl: "https://stufaps.chedroxi.com/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "PESFA - Private Education Student Financial Assistance",
      provider: "Commission on Higher Education",
      description: "The Private Education Student Financial Assistance (PESFA) program provides tuition subsidies for students enrolled in private higher education institutions. It includes book allowance and stipend support. Designed for financially disadvantaged students who wish to pursue college education in private HEIs.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Tuition subsidy for private HEIs, book allowance, stipend",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 80,
      maxAnnualIncome: 300000,
      priorityCourses: "BS Accountancy, BS Engineering, BS Computer Science, BS Information Technology, BS Nursing, BS Medical Technology, BS Pharmacy, BS Agriculture, BS Education, BS Social Work, BS Psychology, BS Biology, BS Chemistry, BS Hospitality Management, BS Tourism Management, BS Criminology",
      requirements: "Filipino citizen, financially disadvantaged, graduating SHS student or currently enrolled in private HEI, good moral character, must not be a recipient of any other government scholarship",
      deadline: "AY 2025-2026 applications are now CLOSED (deadline was June 20, 2025). Next cycle typically opens May-June annually via CHED Regional Offices.",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://stufaps.chedroxi.com/",
      isActive: true,
      isAcceptingApplications: false,
    },

    // ═══════════════════════════════════════════════════════════════
    // FROM GLOBE BLOG - NEW SCHOLARSHIPS
    // ═══════════════════════════════════════════════════════════════
    {
      name: "OWWA Education for Development Scholarship Program (EDSP)",
      provider: "Overseas Workers Welfare Administration",
      description: "The OWWA EDSP provides educational assistance of up to ₱60,000 per year to qualified dependents of OFWs who are in the top 1,000 of the DOST national exams. This scholarship supports college education for children of active OWWA member OFWs.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Up to ₱60,000 per year for tuition and other school fees",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 85,
      maxAnnualIncome: null,
      priorityCourses: "All CHED-recognized degree programs",
      requirements: "Filipino citizen, dependent of an active OWWA member OFW, must be in the top 1,000 of DOST national exams, enrolled in any 4-5 year baccalaureate course, good moral character",
      deadline: "Applications open per AY as announced by OWWA; check OWWA website for current schedule",
      examType: "aptitude",
      examSubjects: "DOST National Exam (Science, Mathematics, English)",
      websiteUrl: "https://owwa.gov.ph/programs-services/education-training/",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "OWWA Dependent Scholarship Program (ODSP)",
      provider: "Overseas Workers Welfare Administration",
      description: "The OWWA ODSP provides ₱20,000 per year to qualified dependents of OFWs who earn less than OWWA's income guidelines. This need-based scholarship supports the college education of children of low-income OFW members.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "₱20,000 per year for tuition and other school fees",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 80,
      maxAnnualIncome: null,
      priorityCourses: "All CHED-recognized degree programs",
      requirements: "Filipino citizen, dependent of an active OWWA member OFW, family income below OWWA guidelines, enrolled in any 4-5 year baccalaureate course, good moral character",
      deadline: "Applications open per AY as announced by OWWA; check OWWA website for current schedule",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://owwa.gov.ph/programs-services/education-training/",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "OWWA Congressional Migrant Workers Scholarship Program (CMWSP)",
      provider: "Overseas Workers Welfare Administration",
      description: "The CMWSP provides up to ₱60,000 per year for migrant workers or their descendants pursuing Science and Technology courses. This scholarship is funded by PCSO via OWWA and supports dependents of OFWs in S&T priority programs.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Up to ₱60,000 per year for tuition, other school fees, and stipend",
      eligibleStrands: "STEM",
      minGPA: 85,
      maxAnnualIncome: null,
      priorityCourses: "BS Computer Science, BS Information Technology, BS Engineering, BS Mathematics, BS Physics, BS Chemistry, BS Biology, BS Statistics, BS Environmental Science, BS Food Technology, BS Agriculture, BS Medical Technology, BS Pharmacy",
      requirements: "Filipino citizen, dependent of a migrant worker/OFW, pursuing Science and Technology courses, good moral character, must pass qualifying exam",
      deadline: "Applications open per AY as announced by OWWA; check OWWA website for current schedule",
      examType: "aptitude",
      examSubjects: "Science, Mathematics, English",
      websiteUrl: "https://owwa.gov.ph/programs-services/education-training/",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "OWWA Education and Livelihood Assistance Program (ELAP)",
      provider: "Overseas Workers Welfare Administration",
      description: "The OWWA ELAP provides up to ₱10,000 per year in college assistance to dependents of deceased OFWs who were active OWWA members at the time of death, or dependents of OFWs who were sentenced to death abroad with at least one OWWA contribution. This program supports both education and livelihood needs of bereaved OFW families.",
      scholarshipType: "government",
      coverage: "partial",
      coverageDetails: "Up to ₱10,000 per year for college assistance",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 75,
      maxAnnualIncome: null,
      priorityCourses: "All CHED-recognized degree programs",
      requirements: "Filipino citizen, dependent of a deceased OFW who was an active OWWA member at time of death, or dependent of OFW sentenced to death abroad with at least one OWWA contribution, enrolled in college, good moral character",
      deadline: "Applications accepted year-round at OWWA Regional Offices",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://owwa.gov.ph/programs-services/education-training/",
      isActive: true,
      isAcceptingApplications: true,
    },
    {
      name: "Ayala Foundation U-Go Scholarship",
      provider: "Ayala Foundation, Inc.",
      description: "The Ayala Foundation U-Go Scholarship supports deserving female students in public colleges and universities. It provides ₱40,000 per year and is renewable as long as the scholar maintains good academic standing. This program empowers women through education in public institutions including PUP.",
      scholarshipType: "private",
      coverage: "partial",
      coverageDetails: "₱40,000 per year for tuition and school-related expenses, renewable with good academic standing",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 85,
      maxAnnualIncome: 300000,
      priorityCourses: "All degree programs in public colleges and universities",
      requirements: "Female Filipino student, enrolled in a public university or college, GWA of at least 85% with no failing grades, not a recipient of any other scholarship, able to demonstrate financial need",
      deadline: "Applications typically open February-March annually; contact Ayala Foundation for current schedule",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.ayalafoundation.org/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "LANDBANK Iskolar ng LANDBANK Program",
      provider: "Land Bank of the Philippines",
      description: "The Iskolar ng LANDBANK program helps children and grandchildren of farmers and fishermen in the country's 60 poorest provinces. The scholarship covers tuition and provides an allowance. It aims to support the education of dependents from the agricultural sector who are top-performing students.",
      scholarshipType: "government",
      coverage: "full",
      coverageDetails: "Full tuition and fees, monthly allowance, book allowance",
      eligibleStrands: "STEM, ABM, HUMSS, GAS, TVL",
      minGPA: 85,
      maxAnnualIncome: 300000,
      priorityCourses: "BS Agriculture, BS Agricultural Engineering, BS Agricultural Economics, BS Forestry, BS Fisheries, BS Veterinary Medicine, BS Environmental Science, BS Food Technology, BS Biology, BS Chemistry, BS Accountancy, BS Business Administration, BS Economics, BS Computer Science, BS Information Technology",
      requirements: "Filipino citizen, child or grandchild of an agrarian reform beneficiary or small farmer/fisher, recommended by a LANDBANK client cooperative/association, top-performing graduating high school student endorsed by school principal, not receiving other scholarships, annual family income not exceeding ₱300,000",
      deadline: "Applications typically open March-May annually; contact LANDBANK for current schedule",
      examType: "none",
      examSubjects: null,
      websiteUrl: "https://www.landbank.com/",
      isActive: true,
      isAcceptingApplications: false,
    },
    {
      name: "UA&P Merit Scholarship",
      provider: "University of Asia and the Pacific",
      description: "The UA&P Merit Scholarship provides up to 100% tuition and other fees coverage for top applicants with at least a 90% high school average and 90th percentile UA&P Entrance Exam (UAPEE) scores. The Dr. Placido L. Mapa Scholarship Endowment offers 100% tuition and miscellaneous fees, a 10-month ₱8,000 monthly stipend, internet allowance, a laptop, and a professional development coach (by nomination, no separate application). Financial assistance is also available for students with family income below ₱800,000.",
      scholarshipType: "merit",
      coverage: "full",
      coverageDetails: "Up to 100% tuition and other fees for merit scholars; Dr. Placido L. Mapa Endowment includes 100% tuition, ₱8,000/month stipend, laptop, internet allowance; Financial Aid for need-based students up to 100% tuition",
      eligibleStrands: "STEM, ABM, HUMSS, GAS",
      minGPA: 90,
      maxAnnualIncome: 800000,
      priorityCourses: "BS Management, BS Entrepreneurship, BS Economics, BS Information Technology, AB Communication, AB Economics, AB Humanities, BS Legal Management, BS Marketing Management",
      requirements: "Filipino citizen, at least 90% high school average, must pass UA&P Entrance Exam (UAPEE) with 90th percentile score for merit scholarship, good moral character. Financial aid applicants: family income below ₱800,000, 85% average, 85th percentile UAPEE score",
      deadline: "Applications typically open August-February annually; contact UA&P Admissions for current schedule",
      examType: "academic",
      examSubjects: "Mathematics, English, Abstract Reasoning",
      websiteUrl: "https://uap.asia/",
      isActive: true,
      isAcceptingApplications: false,
    },
  ];

  for (const scholarship of scholarships) {
    await db.scholarship.create({ data: scholarship });
  }

  console.log(`Seeded ${scholarships.length} scholarships`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
